In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand()

0.15075834882728323

In [11]:
np.random.randn(25)

array([ 0.57052508, -0.85840706,  0.88988986, -0.96167262, -0.53233951,
       -0.37606951,  0.61530467,  0.71073072, -1.35977346,  1.38815752,
       -0.15091095, -0.18841898,  0.81984024,  1.1679609 ,  0.51146725,
       -1.06655402,  1.32234593,  0.99879573, -0.05486067,  0.60145088,
       -0.08371815,  0.24289421, -1.63726871, -0.15807887, -0.35519478])

In [12]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr[3,4]

np.int64(20)

In [15]:
arr.sum()

np.int64(325)

In [16]:
arr.std()

np.float64(7.211102550927978)

In [17]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [18]:
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
arr[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [20]:
arr[4]

array([21, 22, 23, 24, 25])

In [21]:
arr[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [23]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])